name: Bug 反馈
description: 报告可能的异常行为
title: '[BUG] '
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        请填写以下表格来提交 Bug。
  - type: input
    id: system-version
    attributes:
      label: 系统版本
      description: 运行 QQNT 的系统版本
      placeholder: Windows 10 Pro Workstation 22H2
    validations:
      required: true
  - type: input
    id: qqnt-version
    attributes:
      label: QQNT 版本
      description: 可在 QQNT 的关于或设置页中找到
      placeholder: 9.9.7-21804
    validations:
      required: true
  - type: input
    id: llbot-version
    attributes:
      label: LLBot 版本
      description:
      placeholder: 6.6.0
    validations:
      required: true
  - type: input
    id: onebot-client-version
    attributes:
      label: OneBot 客户端
      description: 连接至 LLOneBot 的客户端版本信息
      placeholder: Overflow 2.16.0-2cf7991-SNAPSHOT
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么?
      description: 填写你认为的 LLBot 的不正常行为
    validations:
      required: true
  - type: textarea
    id: how-reproduce
    attributes:
      label: 如何复现
      description: 填写应当如何操作才能触发这个不正常行为
      placeholder: |
        1. xxx
        2. xxx
        3. xxx
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: 期望的结果?
      description: 填写你认为 LLBot 应当执行的正常行为
    validations:
      required: true
  - type: textarea
    id: llonebot-log
    attributes:
      label: LLBot 运行日志
      description:
      render: shell
  - type: textarea
    id: onebot-client-log
    attributes:
      label: OneBot 客户端运行日志
      description: 粘贴 OneBot 客户端的相关日志内容到此处
      render: shell
